/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.30).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Board;
import io.swagger.model.Error;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-12-04T12:00:03.264Z[GMT]")
@Validated
public interface BoardApi {

    @Operation(summary = "", description = "Returns all available task boards", tags={ "boards" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "A list of boards.", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Board.class)))) })
    @RequestMapping(value = "/board",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Board>> boardGet();


    @Operation(summary = "Add a new board", description = "", tags={ "boards" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Expected response to a valid creation request", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Board.class))),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/board",
        produces = { "application/json" }, 
        consumes = { "*/*" }, 
        method = RequestMethod.POST)
    ResponseEntity<Board> createTaskBoard(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Board body);


    @Operation(summary = "Delete a specific board", description = "", tags={ "boards" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid board Id supplied"),
        
        @ApiResponse(responseCode = "404", description = "Board not found") })
    @RequestMapping(value = "/board/{boardId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteBoardById(@Parameter(in = ParameterIn.PATH, description = "The id of the board to delete", required=true, schema=@Schema()) @PathVariable("boardId") Integer boardId);


    @Operation(summary = "Info for a specific board", description = "", tags={ "boards" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Board.class))),
        
        @ApiResponse(responseCode = "404", description = "Board not found"),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/board/{boardId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Board> showBoardById(@Parameter(in = ParameterIn.PATH, description = "The id of the board to retrieve", required=true, schema=@Schema()) @PathVariable("boardId") Integer boardId);


    @Operation(summary = "Info for a specific named board (or boards)", description = "", tags={ "boards" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "A list of matching boards.", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Board.class)))),
        
        @ApiResponse(responseCode = "404", description = "Board not found"),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/board/byName/{boardName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Board>> showBoardByName(@Size(max=20) @Parameter(in = ParameterIn.PATH, description = "The (partial) name of the board to retrieve", required=true, schema=@Schema()) @PathVariable("boardName") String boardName);


    @Operation(summary = "Info for boards owned by an individual", description = "", tags={ "boards" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "A list of matching boards.", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Board.class)))),
        
        @ApiResponse(responseCode = "404", description = "Board not found"),
        
        @ApiResponse(responseCode = "200", description = "unexpected error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))) })
    @RequestMapping(value = "/board/byOwner/{ownerName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Board>> showBoardByOwner(@Size(min=5,max=30) @Parameter(in = ParameterIn.PATH, description = "The name of the owners boards to retrieve", required=true, schema=@Schema()) @PathVariable("ownerName") String ownerName);


    @Operation(summary = "Modify an existing board", description = "", tags={ "boards" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Expected response to a valid update request"),
        
        @ApiResponse(responseCode = "400", description = "Invalid board Id supplied"),
        
        @ApiResponse(responseCode = "404", description = "Board not found"),
        
        @ApiResponse(responseCode = "405", description = "Validation error") })
    @RequestMapping(value = "/board",
        consumes = { "*/*" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateBoardById(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Board body);

}

